#!/bin/bash

configure_sysfsutils()
{
	local p=`cat /proc/cpuinfo | grep -E "^processor\s*:"|wc -l`
	for i in `seq 0 $(($p - 1))`
	do
		echo mode devices/system/cpu/cpu$i/cpufreq/cpuinfo_cur_freq = 440
		echo owner devices/system/cpu/cpu$i/cpufreq/cpuinfo_cur_freq = root:cpufreq
		echo mode devices/system/cpu/cpu$i/cpufreq/scaling_setspeed = 664
		echo owner devices/system/cpu/cpu$i/cpufreq/scaling_setspeed = root:cpufreq

		if [ "$i" != "0" ]
		then
			echo mode devices/system/cpu/cpu$i/online = 664
			echo owner devices/system/cpu/cpu$i/online = root:hotplug
		fi

		echo mode devices/system/cpu/cpufreq/policy$i/scaling_governor = 664
		echo owner devices/system/cpu/cpufreq/policy$i/scaling_governor = root:cpufreq

		for j in `seq 0 $(( $(ls -d /sys/devices/system/cpu/cpu$i/cpuidle/state* | wc -l) - 1 ))`
		do
			echo mode devices/system/cpu/cpu$i/cpuidle/state$j/disable = 664
			echo owner devices/system/cpu/cpu$i/cpuidle/state$j/disable = root:cpuidle
		done; 
done;

echo devices/system/cpu/cpuidle/current_governor = menu
}

add_group()
{
	local GRP=$1
	local USERNAME=$2

	addgroup --system $GRP
	usermod -a -G $GRP $USERNAME
}

configure_sudo()
{
	FILENAME=$1
	echo '%sysfs  ALL = (root) NOPASSWD: /etc/init.d/sysfsutils' > $FILENAME
	chmod 440 $FILENAME
}

do_config()
{
	local USERNAME=$1
	if [ "$UID" != "0" ]
	then
		echo This script requires root priviledges. Please run as root or using sudo. >&2
		exit 1
	fi

	## Add groups
	add_group cpufreq $USERNAME
	add_group cpuidle $USERNAME
	add_group hotplug $USERNAME
	add_group sysfs $USERNAME

	## Generate sysfsutils configuration file
	configure_sysfsutils > /etc/sysfs.d/50-drake.conf
	/etc/init.d/sysfsutils restart

	## Generate password-less sudo privilege to restart sysfsutils
	configure_sudo /etc/sudoers.d/drake
}

USR=$1

if [ "$USR" == "" ]
then
	if [ "$UID" == "0" ]
	then
		echo Setting up privileges for superuser. You probably want to set up privileges for a normal user\; if so, please give its username as first argument and run this script again >&2
	else
		echo This requires superuser privileges. Trying with sudo. >&2
	fi
	sudo $0 $USER
	exit $?
else
	if [ "$UID" != "0" ]
	then
		echo This requires superuser privileges. Trying with sudo. >&2
		sudo $0 $USR
		exit $?
	else
		do_config $USR
		echo Configuration done.
		echo You might need to logout and login again before all new settings take effect.
		echo Don\'t forget to add options \"intel_idle.max_cstate=0 cpuidle_sysfs_switch=1 intel_pstate=disable\" to your kernel before using drake.
	fi
fi

